[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fair_launch_dex = "Boed7wGmYbwngxJtPdRNZszZdeg778GdpExrjy5rsdZu"
meme_token = "23LyvPH8FiDapwARhYs39d2qtkNpYyeRycRndbxPXYVz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
